Gormv2: # 只针对 gorm  操作数据库有效
  UseDbType: "mysql"  # 备选项 mysql 、sqlserver、 postgresql
  Mysql:
    IsInitGlobalGormMysql: 0    # 随项目启动为gorm db初始化一个全局 variable.GormDbMysql（完全等于*gorm.Db）,正确配置数据库，该值必须设置为: 1
    SlowThreshold: 30            # 慢 SQL 阈值(sql执行时间超过此时间单位（秒），就会触发系统日志记录)
    Write:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 3306
      Prefix: "tb_"   #  目前没有用到该配置项
      User: "root"
      Pass: "DRsXT5ZJ6Oi55LPQ"
      Charset: "utf8"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60    # 连接不活动时的最大生存时间(秒)
      #ReConnectInterval: 1    # 保留项,重连数据库间隔秒数
      #PingFailRetryTimes: 3   # 保留项,最大重连次数
    IsOpenReadDb: 0                     # 是否开启读写分离配置（1=开启、0=关闭），IsOpenReadDb=1,Read 部分参数有效，否则Read部分参数直接忽略
    Read:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 3308                        #注意，非3306，请自行调整
      Prefix: "tb_"
      User: "root"
      Pass: "yourPassword"
      Charset: "utf8"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
  # 如果要使用sqlserver数据库，请在 app/model 目录，将 users_for_sqlserver.txt 的内容直接覆盖同目录的 users.go 即可
  SqlServer:
    # 随项目启动为gorm db初始化一个全局 variable.GormDbMysql（完全等于*gorm.Db）,正确配置数据库，该值必须设置为: 1
    # 此外，开启 sqlserver 数据库时，请在 app/model/users_for_sqlserver.txt  文件中，按照说明手动替换一下代码
    IsInitGlobalGormSqlserver: 0
    SlowThreshold: 30
    Write:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 1433
      Prefix: "tb_"
      User: "Sa"
      Pass: "secret2017"
      #ReConnectInterval: 1    # 保留项,重连数据库间隔秒数
      #PingFailRetryTimes: 3   # 保留项,最大重连次数
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
    IsOpenReadDb: 0            # 是否开启读写分离配置（1=开启、0=关闭），IsOpenReadDb=1,Read  部分参数有效，否则Read部分参数直接忽略
    Read:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 1433
      Prefix: "tb_"
      User: "Sa"
      Pass: "secret2017"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
  # 如果要使用postgresql数据库，请在 app/model 目录，将 users_for_postgres.txt 的内容直接覆盖同目录的 users.go 即可
  PostgreSql:
    IsInitGlobalGormPostgreSql: 0  # 随项目启动为gorm db初始化一个全局 variable.GormDbMysql（完全等于*gorm.Db）,正确配置数据库，该值必须设置为: 1
    SlowThreshold: 30
    Write:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 5432
      Prefix: "tb_"
      User: "postgres"
      Pass: "Secret2017~"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
    #ReConnectInterval: 1    # 保留项,重连数据库间隔秒数
    #PingFailRetryTimes: 3   # 保留项,最大重连次数
    IsOpenReadDb: 0            # 是否开启读写分离配置（1=开启、0=关闭），IsOpenReadDb=1,Read  部分参数有效，否则Read部分参数直接忽略
    Read:
      Host: "127.0.0.1"
      DataBase: "db_goskeleton"
      Port: 5432
      Prefix: "tb_"
      User: "postgres"
      Pass: "secret2017"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60
